/* crypto.h — the only cryptography in Herus, and all of it.
 *
 * SHA-256, HMAC-SHA256, HKDF, ChaCha20, Poly1305, ChaCha20-Poly1305 AEAD.
 * Portable C99, no allocation, no static mutable state, no libc beyond string.h.
 *
 * WHY IMPLEMENT INSTEAD OF LINKING
 * --------------------------------
 * The same bytes must be produced by three things: this firmware, the host test
 * suite, and mbedTLS-on-ESP-IDF if we ever switch. A ~600-line self-contained
 * implementation is auditable in an afternoon and identical everywhere. The risk
 * of hand-rolled crypto is implementation error, not algorithm choice — so the
 * mitigation is differential testing: test_net.c checks every primitive against
 * RFC vectors AND against 400 random cases generated by Python `cryptography`
 * (tools/gen_vectors.py). A primitive that disagrees with an independent
 * implementation on random input fails the build.
 *
 * WHAT IS DELIBERATELY ABSENT
 * ---------------------------
 * No public-key code. P-256 ECDH/ECDSA lives in the ATECC608A (identity), which
 * is the only place a long-term secret is allowed to exist. This file is the
 * symmetric half of the ratchet, exactly as docs/02-PROTOCOL.md §4.1 describes.
 * Do not add a software P-256 here: a scalar in MCU RAM is the whole thing the
 * secure element exists to prevent.
 */
#ifndef HERUS_CRYPTO_H
#define HERUS_CRYPTO_H

#include <stdint.h>
#include <stddef.h>

/* ---------------- SHA-256 ---------------- */
#define SHA256_LEN 32
typedef struct {
    uint32_t h[8];
    uint64_t len;
    uint8_t  buf[64];
    size_t   n;
} sha256_ctx;

void sha256_init(sha256_ctx *c);
void sha256_update(sha256_ctx *c, const void *data, size_t len);
void sha256_final(sha256_ctx *c, uint8_t out[SHA256_LEN]);
void sha256(const void *data, size_t len, uint8_t out[SHA256_LEN]);

/* ---------------- HMAC-SHA256 ---------------- */
void hmac_sha256(const uint8_t *key, size_t keylen,
                 const void *msg, size_t msglen,
                 uint8_t out[SHA256_LEN]);

/* ---------------- HKDF-SHA256 (RFC 5869) ----------------
 * Extract-then-expand. `salt` may be NULL (treated as 32 zero bytes), `info`
 * may be NULL. okm_len <= 255*32. Returns 0 on success, -1 on a length error. */
void hkdf_extract(const uint8_t *salt, size_t saltlen,
                  const uint8_t *ikm, size_t ikmlen,
                  uint8_t prk[SHA256_LEN]);
int  hkdf_expand(const uint8_t prk[SHA256_LEN],
                 const void *info, size_t infolen,
                 uint8_t *okm, size_t okmlen);
int  hkdf(const uint8_t *salt, size_t saltlen,
          const uint8_t *ikm, size_t ikmlen,
          const void *info, size_t infolen,
          uint8_t *okm, size_t okmlen);

/* ---------------- ChaCha20 (RFC 8439) ----------------
 * 32-byte key, 12-byte nonce, 32-bit block counter. Encrypt and decrypt are the
 * same call. `counter` is the initial block counter: RFC 8439 AEAD uses 0 for
 * the Poly1305 key block and 1 for the first plaintext block.
 *
 * Returns 0, or -1 (writing nothing) if the request would advance the block
 * counter past 2^32 - 1. RFC 8439 caps a message at 256 GB and says nothing
 * about what happens after; OpenSSL propagates the carry into the nonce words,
 * a strict implementation wraps to zero, and the two then produce different
 * keystreams from the same inputs. Herus frames are at most 168 bytes, so the
 * boundary is unreachable — and refusing it here is how it STAYS unreachable
 * instead of becoming an interop bug in someone's port five years from now. */
int  chacha20_xor(const uint8_t key[32], const uint8_t nonce[12],
                  uint32_t counter, const uint8_t *in, uint8_t *out, size_t len);

/* ---------------- Poly1305 ---------------- */
#define POLY1305_TAG_LEN 16
void poly1305_mac(const uint8_t key[32], const void *msg, size_t len,
                  uint8_t tag[POLY1305_TAG_LEN]);

/* ---------------- AEAD ----------------
 * ChaCha20-Poly1305 as in RFC 8439 §2.8. `tag_len` may be 16 or, as Herus uses
 * it on air, 8.
 *
 * A 64-bit tag gives 2^-64 forgery probability PER ATTEMPT. That is adequate
 * only with a receive-side attempt limit, which is why session.c owns a token
 * bucket and why footgun #9 exists. Truncation without rate limiting is not a
 * byte saving, it is a downgrade. */
void aead_encrypt(const uint8_t key[32], const uint8_t nonce[12],
                  const uint8_t *aad, size_t aadlen,
                  const uint8_t *pt, size_t ptlen,
                  uint8_t *ct, uint8_t *tag, size_t tag_len);

/* Returns 0 if the tag verifies (and writes ptlen bytes to pt), -1 otherwise.
 * On failure pt is zeroed: releasing unauthenticated plaintext to a caller who
 * forgets to check the return value is the classic AEAD misuse. */
int  aead_decrypt(const uint8_t key[32], const uint8_t nonce[12],
                  const uint8_t *aad, size_t aadlen,
                  const uint8_t *ct, size_t ctlen,
                  const uint8_t *tag, size_t tag_len,
                  uint8_t *pt);

/* ---------------- utilities ---------------- */
/* Constant-time equality. Returns 1 if equal. A byte-by-byte early-out compare
 * on a MAC leaks the length of the correct prefix, which is enough to forge one
 * byte at a time. */
int  ct_eq(const void *a, const void *b, size_t len);
/* Best-effort scrub that the optimiser is not allowed to elide. */
void secure_zero(void *p, size_t len);

#endif /* HERUS_CRYPTO_H */
