#!/usr/bin/env python3
"""gen_vectors.py — generate differential test vectors for firmware/net/crypto.c.

Hand-written crypto fails through implementation error, not algorithm choice, so
the mitigation is differential testing against an independent implementation.
This script asks Python's `cryptography` (OpenSSL underneath) for the answer on
random inputs and writes them as a C header the proof suite compiles in.

Deterministic by design: a fixed seed means the committed vectors.h is stable and
a diff is meaningful. Re-run only to widen coverage.

    python3 tools/gen_vectors.py > firmware/test/vectors.h

Requires: pip3 install cryptography   (already present on this bench: 45.0.7)
"""
import hashlib
import hmac as _hmac
import random
import sys

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
from cryptography.hazmat.primitives.poly1305 import Poly1305
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives import hashes

N = 50                      # cases per primitive
SEED = 0x48455255_53303032  # "HERUS002"


def carr(b):
    return "{" + ",".join("0x%02x" % x for x in b) + "}"


def emit(name, rows, fields):
    print("static const struct { %s } %s[] = {" % (fields, name))
    for r in rows:
        print("  { %s }," % r)
    print("};")
    print("#define %s_N ((int)(sizeof(%s)/sizeof(%s[0])))" % (name.upper(), name, name))
    print()


def main():
    rnd = random.Random(SEED)
    R = rnd.randbytes

    print("/* vectors.h — GENERATED by tools/gen_vectors.py. DO NOT EDIT.")
    print(" * Independent reference: Python `cryptography` (OpenSSL). Seed 0x%x." % SEED)
    print(" * If a case here fails, crypto.c is wrong — the reference is not. */")
    print("#ifndef HERUS_VECTORS_H\n#define HERUS_VECTORS_H\n#include <stdint.h>\n")

    # ---- SHA-256 ----
    rows = []
    for _ in range(N):
        n = rnd.randrange(0, 200)
        m = R(n) if n else b""
        rows.append("%d, %s, %s" % (n, carr(m or b"\0"), carr(hashlib.sha256(m).digest())))
    emit("V_SHA256", rows, "int len; uint8_t msg[200]; uint8_t md[32];")

    # ---- HMAC-SHA256 ----
    rows = []
    for _ in range(N):
        kl = rnd.randrange(1, 100)
        ml = rnd.randrange(0, 200)
        k, m = R(kl), (R(ml) if ml else b"")
        rows.append("%d, %s, %d, %s, %s" % (
            kl, carr(k), ml, carr(m or b"\0"),
            carr(_hmac.new(k, m, hashlib.sha256).digest())))
    emit("V_HMAC", rows, "int klen; uint8_t key[100]; int mlen; uint8_t msg[200]; uint8_t md[32];")

    # ---- HKDF-SHA256 ----
    rows = []
    for _ in range(N):
        il, sl, fl = rnd.randrange(1, 64), rnd.randrange(0, 40), rnd.randrange(0, 40)
        ikm, salt, info = R(il), (R(sl) if sl else b""), (R(fl) if fl else b"")
        ol = rnd.choice([16, 32, 42, 64, 96])
        okm = HKDF(algorithm=hashes.SHA256(), length=ol,
                   salt=salt or None, info=info).derive(ikm)
        rows.append("%d, %s, %d, %s, %d, %s, %d, %s" % (
            il, carr(ikm), sl, carr(salt or b"\0"), fl, carr(info or b"\0"),
            ol, carr(okm)))
    emit("V_HKDF", rows,
         "int ilen; uint8_t ikm[64]; int slen; uint8_t salt[40]; "
         "int flen; uint8_t info[40]; int olen; uint8_t okm[96];")

    # ---- ChaCha20 ----
    # cryptography's ChaCha20 nonce is counter(4,LE) || nonce(12).
    #
    # Counters that would cross the 32-bit wrap are deliberately excluded: the
    # RFC leaves that case undefined, OpenSSL carries into the nonce, and
    # crypto.c refuses it outright (see chacha20_xor). 0xffffffff with a
    # single-block length is included because that IS defined and is the last
    # legal block.
    rows = []
    for _ in range(N):
        key, nonce = R(32), R(12)
        ctr = rnd.choice([0, 1, 2, 0xffffffff])
        pl = rnd.randrange(1, 200) if ctr != 0xffffffff else rnd.randrange(1, 65)
        pt = R(pl)
        c = Cipher(algorithms.ChaCha20(key, ctr.to_bytes(4, "little") + nonce), None)
        ct = c.encryptor().update(pt)
        rows.append("%s, %s, %uu, %d, %s, %s" % (
            carr(key), carr(nonce), ctr, pl, carr(pt), carr(ct)))
    emit("V_CHACHA", rows,
         "uint8_t key[32]; uint8_t nonce[12]; uint32_t ctr; int len; "
         "uint8_t pt[200]; uint8_t ct[200];")

    # ---- Poly1305 ----
    rows = []
    for _ in range(N):
        key = R(32)
        ml = rnd.randrange(0, 200)
        m = R(ml) if ml else b""
        p = Poly1305(key); p.update(m)
        rows.append("%s, %d, %s, %s" % (carr(key), ml, carr(m or b"\0"), carr(p.finalize())))
    emit("V_POLY", rows, "uint8_t key[32]; int len; uint8_t msg[200]; uint8_t tag[16];")

    # ---- ChaCha20-Poly1305 AEAD ----
    rows = []
    for _ in range(N):
        key, nonce = R(32), R(12)
        al, pl = rnd.randrange(0, 32), rnd.randrange(1, 64)
        aad, pt = (R(al) if al else b""), R(pl)
        out = ChaCha20Poly1305(key).encrypt(nonce, pt, aad or None)
        ct, tag = out[:pl], out[pl:]
        rows.append("%s, %s, %d, %s, %d, %s, %s, %s" % (
            carr(key), carr(nonce), al, carr(aad or b"\0"), pl, carr(pt),
            carr(ct), carr(tag)))
    emit("V_AEAD", rows,
         "uint8_t key[32]; uint8_t nonce[12]; int alen; uint8_t aad[32]; "
         "int plen; uint8_t pt[64]; uint8_t ct[64]; uint8_t tag[16];")

    print("#endif /* HERUS_VECTORS_H */")


if __name__ == "__main__":
    sys.exit(main())
